// Error messages actions
export const ERROR_FETCHING = "ERROR_FETCHING";

// APP Actions
export const GETTING_CURRENT_LOCATION_START = "GETTING_CURRENT_LOCATION_START";
export const GETTING_CURRENT_LOCATION_END = "GETTING_CURRENT_LOCATION_END";
export const CURRENT_LOCATION = "CURRENT_LOCATION";

export const NOTIFICATION_SET = "NOTIFICATION_SET";
export const NOTIFICATION_REMOVE = "NOTIFICATION_REMOVE";

// Maps actions
export const MAP_ZOOM_CHANGED = "MAP_ZOOM_CHANGED";
export const MAP_CENTER_CHANGED = "MAP_CENTER_CHANGED";

// Events actions
export const SEARCH_EVENT = "SEARCH_EVENT";
export const SEARCH_EVENT_NOT_FOUND = "SEARCH_EVENT_NOT_FOUND";

export const FETCH_EVENTS_STARTED = "FETCH_EVENTS_STARTED";
export const FETCH_EVENTS_ENDED = "FETCH_EVENTS_ENDED";
export const FETCH_EVENTS = "FETCH_EVENTS";

export const SELECT_EVENT_STARTED = "SELECT_EVENT_STARTED";
export const SELECT_EVENT_ENDED = "SELECT_EVENT_ENDED";
export const SELECT_EVENT = "SELECT_EVENT";

// Categories Actions
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const SELECT_CATEGORY = "SELECT_CATEGORY";

// Distances Actions
export const SELECT_RANGE = "SELECT_RANGE";
