export const MAP_CENTER_CHANGED = "MAP_CENTER_CHANGED";

// Events actions
export const SEARCH_EVENT = 'SEARCH_EVENT';
export const SEARCH_EVENT_NOT_FOUND = 'SEARCH_EVENT_NOT_FOUND';
export const FETCHING_EVENTS = "FETCHING_EVENTS";
export const FETCH_EVENTS = "FETCH_EVENTS";
export const SELECT_EVENT = "SELECT_EVENT";